#!/bin/bash

VPN_GATEWAY=$(netstat -nr -f inet | grep "1.1.1.1" | awk '{print $2}')
FIRST_SEC=$(echo $VPN_GATEWAY | awk -F '.' '{print $1}')
VPN_DEST=${FIRST_SEC}.0.0.0

sudo route delete default
##sudo route add default 1.1.1.1
sudo route add default 192.168.0.1
##sudo route add default 10.20.21.1
sudo route add -net ${VPN_DEST} ${VPN_GATEWAY}
netstat -nr -f inet
