#!/usr/bin/env bash
# Reset routing table on OSX

# display current routing table
echo "********** BEFORE ****************************************"
netstat -nr -f inet
echo "**********************************************************"

for i in {0..4}; do
  sudo route -n flush # several times
done

echo "********** AFTER *****************************************"
netstat -nr -f inet
echo "**********************************************************"

echo "Bringing interface down..."
sudo ifconfig en4 down
sleep 1
echo "Bringing interface back up..."
sudo ifconfig en4 up
sleep 1

echo "********** FINALLY ***************************************"
netstat -nr -f inet
echo "**********************************************************"
